travault/agent_support/urls.py
# agent_support/urls.py
from django.urls import path
from . import views

app_name = 'agent_support'

urlpatterns = [
    path('', views.agent_support_home, name='agent_support_home'),
    path('add-supplier/', views.add_agent_support_supplier, name='add_supplier'),
    path('edit-supplier/<int:id>/', views.edit_supplier, name='edit_supplier'),  # Edit route
    path('delete-supplier/<int:id>/', views.delete_supplier, name='delete_supplier'),  # Delete route
    
]

travault/crm/urls.py
from django.urls import path
from . import views

app_name = 'crm'

urlpatterns = [
    path('', views.index, name='crm_home'),
] # Add this line to your urls.py file in the crm app. This will make the root URL of the crm app point to the index view.

travault/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

travault/travault/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import logout_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('logout/', logout_view, name='logout'),    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('agent_support/', include('agent_support.urls')),
    path('users/', include('users.urls')),  # Add this line
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('crm/', include('crm.urls')),  
]

travault/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'dashboard/index.html')

@login_required
def profile(request):
    return render(request, 'dashboard/profile.html')

@login_required
def dashboard(request):
    return render(request, 'dashboard/index.html') 

travault/dashboard/templates/dashboard/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid full-height-bg bg-gray-200">
    <div class="container dashboard-cards">
        <h1 class="text-center display-3 roboto">Dashboard</h1>
        <div class="row pt-3 justify-content-center">
            <div class="col-12 col-md-6">
                <form class="d-flex ">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-search" type="submit">Search</button>
                </form>
            </div>
        </div>
        <div class="row text-center roboto pt-5">
            <div class="col-sm-12 col-md-4 mb-4">
                <a href="{% url 'agent_support:agent_support_home' %}" class="card-link">
                    <div class="card h-100 shadow card-button">
                        <div class="card-body text-center">
                            <h5 class="card-title">Agent Support</h5>
                            <p class="card-text">Access agent support tools and resources.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-sm-12 col-md-4 mb-4">
                <a href="{% url 'crm:crm_home' %}" class="card-link">
                    <div class="card h-100 shadow card-button">
                        <div class="card-body text-center">
                            <h5 class="card-title">CRM</h5>
                            <p class="card-text">Manage customer relationships and data.</p>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-sm-12 col-md-4 mb-4">
                <a href="#" class="card-link">
                    <div class="card h-100 shadow card-button">
                        <div class="card-body text-center">
                            <h5 class="card-title">View Tickets</h5>
                            <p class="card-text">Access and manage support tickets.</p>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}