travault/crm/urls.py
from django.urls import path
from . import views

app_name = 'crm'

urlpatterns = [
    path('', views.index, name='crm_home'),
] # Add this line to your urls.py file in the crm app. This will make the root URL of the crm app point to the index view.

travault/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

travault/travault/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import logout_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('logout/', logout_view, name='logout'),    
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('agent_support/', include('agent_support.urls')),
    path('users/', include('users.urls')),  # Add this line
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('crm/', include('crm.urls')),  
]

travault/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('manage/', views.manage_users, name='manage_users'),
    path('add/', views.add_user, name='add_user'),
    path('edit/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete/<int:user_id>/', views.delete_user, name='delete_user'),
]

travault/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    {% block meta  %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock  %}

    {% block extra_meta %}
    {% endblock %}

    {% block corecss %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <script src="https://kit.fontawesome.com/39153677d4.js" crossorigin="anonymous"></script>
    {% endblock %}

    {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block corejs %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous">
    </script>
    {% endblock %}

    {% block extra_js %}
    <script src="{% static 'js/script.js' %}"></script>
    {% endblock %}

    <title>TraVault {% block extra_title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg py-0 home-nav fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'images/TraVault_transparent-logo_v2.png' %}" alt="TraVault Logo" height="30"
                    class="d-inline-block align-top logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item pt-1">
                        <a class="nav-link home-nav-text" href="{% url 'dashboard:index' %}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa-solid fa-gear"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="#">Profile</a></li>
                            {% if user.companyuser.is_admin %}
                            <li><a class="dropdown-item" href="{% url 'users:manage_users' %}">Manage Users</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="#">Billing</a></li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/' %}active{% endif %}"
                            aria-current="page" href="#home" data-section="home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/#features' %}active{% endif %}"
                            href="#features" data-section="features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/#about-us' %}active{% endif %}"
                            href="#about-us" data-section="about-us">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/#pricing' %}active{% endif %}"
                            href="#pricing" data-section="pricing">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/custom-registration/' %}active{% endif %}"
                            href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link home-nav-text {% if request.path == '/accounts/login/' %}active{% endif %}"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div id="message-container" class="fixed-top">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block page_header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block postload_js %}
    {% endblock %}


</body>

</html>